services:
  frontend:
    build:
      context: ../carer_front/frontend
      dockerfile: Dockerfile
    volumes:
      - ../carer_front/frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - frontbackend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider

  frontbackend:
    build:
      context: ../carer_front/backend
      dockerfile: Dockerfile
    volumes:
      - ../carer_front/backend:/app
    ports:
      - "5000:5000"
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - CARER_BACKEND_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    build:
      context: ../carer_backend
      dockerfile: Dockerfile
    volumes:
      - ../carer_backend:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/mydatabase
      - SECRET_TOKEN=${SECRET_TOKEN}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:




