services:
  frontend:
    build:
      context: ../socialcarerfront/frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - middleware
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ../socialcarerfront/frontend/src:/app/src 
      - ../socialcarerfront/frontend/public:/app/public
      - /app/node_modules

  middleware:
    build:
      context: ../socialcarerfront/middleware
      dockerfile: Dockerfile

    ports:
      - "5000:5000"
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - CARER_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    volumes:
      - ../socialcarerfront/middleware:/app
      - /app/node_modules  

  backend:
    build:
      context: ../socialcarer
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/mydatabase
      - SECRET_TOKEN=${SECRET_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ../socialcarer:/app
    depends_on:
      - db
      - otel-collector

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"  # Prometheus metrics
    depends_on:
      - loki
      - prometheus
 
volumes:
  db_data:
  grafana-storage:




